ingress:
  # allows you to specify custom hosts
  customHosts:
    hook "https://bbbd-138-117-22-159.ngrok-free.app"
    # specify your ngrok custom domain here
    # such as
    #    hook: "myuniqueid.ngrok.io
    # so that webhooks from, say, github.com, will work to your local laptop
    hook: ""

kaniko:
  # lets support insecure docker registries so that we
  # can use the local docker-registry chart
  flags: "--insecure"
